name: Python Package CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install Language Pack
      run: sudo apt-get install -y language-pack-it

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ".[test]"

    - name: Run tests
      run: |
        pytest

    - name: Build package
      run: |
        python -m pip install wheel
        python setup.py sdist bdist_wheel
